-- ============================================================================
-- 002_tables.sql
-- Core schema for Park Lofts Rent Manager.
--
-- Design principles:
--   - Every primary key is uuid v4, generated by pgcrypto.
--   - Timestamps default to now() and are updated via trigger (004).
--   - Money is stored as numeric with explicit precision.
--   - No text fields for status, enums enforce validity at the DB layer.
--   - ON DELETE rules are explicit per relationship.
--   - Hard constraints (CHECK, UNIQUE, NOT NULL) live in the DB, not the app.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- units, one row per rentable property listed on Park Lofts.
-- ----------------------------------------------------------------------------
create table if not exists public.units (
  id                   uuid primary key default gen_random_uuid(),
  name                 text        not null check (char_length(name) between 2 and 120),
  description          text,
  nightly_rate_usd     numeric(10, 2) not null check (nightly_rate_usd > 0),
  max_guests           smallint    not null default 2 check (max_guests between 1 and 50),
  bedrooms             smallint    check (bedrooms is null or bedrooms between 0 and 20),
  beds                 smallint    check (beds is null or beds between 0 and 40),
  airbnb_listing_url   text        check (airbnb_listing_url is null or airbnb_listing_url ~* '^https?://'),
  airbnb_ical_url      text        not null unique check (airbnb_ical_url ~* '^https?://'),
  image_urls           text[]      not null default '{}'::text[],
  status               unit_status not null default 'active',
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

comment on table public.units is 'Rentable units exposed on the Park Lofts booking widget. One row per listing.';
comment on column public.units.airbnb_ical_url is 'Unique, used by ical-sync to pull remote availability.';
comment on column public.units.image_urls is 'Public URLs from the `units` storage bucket. Minimum 5 enforced at API layer.';

-- ----------------------------------------------------------------------------
-- availability, one row per blocked night per unit.
--
-- `source` distinguishes rows synced from Airbnb from rows created by the
-- booking widget. The sync_availability RPC only deletes rows with
-- source = 'airbnb', so widget bookings survive Airbnb re-syncs.
-- ----------------------------------------------------------------------------
create table if not exists public.availability (
  id            uuid primary key default gen_random_uuid(),
  unit_id       uuid                not null references public.units(id) on delete cascade,
  blocked_date  date                not null,
  source        availability_source not null default 'airbnb',
  created_at    timestamptz         not null default now(),
  unique (unit_id, blocked_date)
);

comment on table public.availability is 'Per-night block list. Blocks originate from Airbnb iCal sync, widget bookings, or manual admin entries.';

-- ----------------------------------------------------------------------------
-- booking_requests, guest-submitted reservation requests.
--
-- A booking moves pending -> approved -> paid (or rejected/cancelled).
-- approved_by references auth.users(id) so admins keep accountability.
-- ----------------------------------------------------------------------------
create table if not exists public.booking_requests (
  id                      uuid           primary key default gen_random_uuid(),
  unit_id                 uuid           not null references public.units(id) on delete restrict,
  guest_name              text           not null check (char_length(guest_name) between 2 and 200),
  guest_email             citext         not null,
  guest_phone             text           not null check (char_length(guest_phone) between 6 and 40),
  check_in_date           date           not null,
  check_out_date          date           not null,
  total_price_usd         numeric(12, 2) not null check (total_price_usd >= 0),
  special_requests        text           check (special_requests is null or char_length(special_requests) <= 2000),
  status                  booking_status not null default 'pending',
  last_sync_at_submission timestamptz    not null default now(),
  approved_by             uuid           references auth.users(id) on delete set null,
  approved_at             timestamptz,
  rejected_at             timestamptz,
  rejection_reason        text,
  created_at              timestamptz    not null default now(),
  updated_at              timestamptz    not null default now(),
  constraint booking_requests_date_range check (check_out_date > check_in_date),
  constraint booking_requests_email_format check (guest_email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

comment on table public.booking_requests is 'Guest booking requests. Lifecycle: pending -> approved -> paid. Rejection/cancellation branches covered.';
comment on column public.booking_requests.last_sync_at_submission is 'Snapshot of last successful Airbnb sync at the moment the guest submitted, used for conflict detection.';

-- ----------------------------------------------------------------------------
-- payments, Bancard vPOS 2.0 records tied to booking_requests.
--
-- shop_process_id is our side, unique, sent to Bancard as Entero(15).
-- bancard_process_id is Bancard's returned process_id.
-- amount_pyg is authoritative for Bancard since only PYG is accepted.
-- ----------------------------------------------------------------------------
create table if not exists public.payments (
  id                    uuid           primary key default gen_random_uuid(),
  booking_id            uuid           not null references public.booking_requests(id) on delete cascade,
  amount_usd            numeric(12, 2) not null check (amount_usd >= 0),
  amount_pyg            numeric(15, 2) check (amount_pyg is null or amount_pyg >= 0),
  shop_process_id       text           unique,
  bancard_process_id    text,
  bancard_transaction_id text,
  payment_status        payment_status not null default 'pending',
  payment_method        payment_method not null default 'bancard',
  is_preauthorization   boolean        not null default false,
  bancard_response      jsonb,
  authorization_number  text,
  response_code         text,
  initiated_at          timestamptz    not null default now(),
  completed_at          timestamptz,
  failed_at             timestamptz,
  failure_reason        text,
  created_at            timestamptz    not null default now(),
  updated_at            timestamptz    not null default now()
);

comment on table public.payments is 'Bancard vPOS 2.0 payment records. One-to-many with booking_requests (rollback + retry creates a new row in newer revisions).';
comment on column public.payments.shop_process_id is 'Unique numeric ID sent to Bancard (Entero 15). Used to find payments during confirmation webhooks.';
comment on column public.payments.bancard_response is 'Raw jsonb of the last Bancard response for audit. Never log private keys here.';

-- ----------------------------------------------------------------------------
-- sync_logs, observability for the iCal sync cron.
-- ----------------------------------------------------------------------------
create table if not exists public.sync_logs (
  id                   uuid        primary key default gen_random_uuid(),
  unit_id              uuid        references public.units(id) on delete cascade,
  ical_url             text        not null,
  sync_started_at      timestamptz not null default now(),
  sync_completed_at    timestamptz,
  sync_status          sync_status not null default 'in_progress',
  blocked_dates_found  integer     check (blocked_dates_found is null or blocked_dates_found >= 0),
  error_message        text,
  created_at           timestamptz not null default now()
);

comment on table public.sync_logs is 'Per-run log of iCal sync attempts. Feeds admin dashboard sync history and alerting.';
